### ISSUE TITLE
Codec missing

### ISSUE THREAD

**Issue by Aeron1** [haecker-felix/Gradio#308]
installing Gradio 7.1 via Gnome Software and Flathub in Fedora 27 Radio streams with AAC and AAC+ cannot be played due to missing codec

![grafik](https://user-images.githubusercontent.com/37975034/38171814-04ed3310-35a1-11e8-80a2-8d29d26dd9d9.png)

**Comment by rogersachan** [comment]
I'm having this issue as well, despite having all of the gstreamer packages installed.

**Comment by rogersachan** [comment]
![image](https://user-images.githubusercontent.com/7173984/38458271-7dc21738-3a6a-11e8-8f01-b045643ebfcf.png)

**Comment by Aeron1** [comment]
i played around with Gradio.app and Gradio.gnome.extension and recognised that with Gradio.gnome.extension those radio stations Gradio.app is missing codecs work fine

**Comment by haecker-felix** [comment]
Can anybody test this package? (Just unzip it, it is a flatpak package)

[de.haeckerfelix.gradio.zip](https://github.com/haecker-felix/Gradio/files/1935927/de.haeckerfelix.gradio.zip)

**Comment by gnumdk** [comment]
Can't test here, it does not want to install and I don't understand why.
BTW, look at https://github.com/flathub/org.gnome.Lollypop/blob/master/org.gnome.Lollypop.json
I guess you need:
```

 {
      "name": "gst-plugins-ugly",
      "config-opts": [ "--disable-gtk-doc"],
      "cleanup": [ "*.la", "/share/gtk-doc" ],
      "sources": [{
        "type": "archive",
        "url": "https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.12.4.tar.xz",
        "sha256": "1c165b8d888ed350acd8e6ac9f6fe06508e6fcc0a3afc6ccc9fbeb30df9be522"
      }]
},
```

**Comment by dantelecan** [comment]
I'm still having this problem on Xubuntu 18.04. Any progress or suggestion regarding this issue?

**Comment by metamanball** [comment]
I am having this problem on ubuntu 18.04. I installed all codecs and gstreamer-plugins, but still it won't play aac-streams.

**Comment by ozzymanborn** [comment]
Same in my ubuntu 18.04
![2018-09-13 19-59-14 ekran goruntusu](https://user-images.githubusercontent.com/30194189/45503493-aa4a4300-b78f-11e8-93a8-84406e39d650.png)

**Comment by haecker-felix** [comment]
Fixed with latest commit. New build should be released soon on Flathub!

https://github.com/flathub/de.haeckerfelix.gradio/commit/c3856091a9489cc8e3e7173ddeec138a60d73541

**Comment by dantelecan** [comment]
This problem still exists in version 7.3 in Ubuntu 18.04. So this commit didn't fix it https://github.com/flathub/de.haeckerfelix.gradio/commit/c3856091a9489cc8e3e7173ddeec138a60d73541
![Screenshot from 2019-09-13 13-23-20](https://user-images.githubusercontent.com/2227120/64856114-f5f52e00-d629-11e9-8773-05321943c231.png)
![Screenshot from 2019-09-13 13-23-52](https://user-images.githubusercontent.com/2227120/64856118-f7265b00-d629-11e9-894f-50c8a3970d7c.png)

**Comment by ferlanero** [comment]
The problem of the missing AAC codec persists on ArchLinux flatpak installation: 

`"Automatic codec installation isn't supported by your distribution. Please install "gstreamer|1.0|gradio|decodificador MPEG-2 AAC|decoder-audio/mpeg, mpegversion=(int)2, level=(string)2, profile=(string)lc"`

But nothing matches it on flathub:

`No remote refs found similar to ‘gstreamer|1.0|gradio|decodificador MPEG-2 AAC|decoder-audio/mpeg, mpegversion=(int)2, level=(string)2, profile=(string)lc’`

![Captura de pantalla de 2019-09-18 01-06-42](https://user-images.githubusercontent.com/1192395/65086098-d4d96800-d9b0-11e9-989a-ad074fa9f79c.png)

![Captura de pantalla de 2019-09-18 01-07-07](https://user-images.githubusercontent.com/1192395/65086120-e15dc080-d9b0-11e9-88ef-4aac62021fcd.png)
