### ISSUE TITLE
Behaviour of Discover button after search

### ISSUE THREAD

**Issue by mohamedsakhri** [haecker-felix/gradio#72]
You can reproduce this bug following this user case:

1. enter something in the search box and click the search icon or enter key
2. the search results are displayed
3. remove the search item from the search box
4. when you click discover the default lists ( most popular, recently played..) should be displayed, but nothing is displayed (see Screenshot)

The discover button should show the default lists when the search box is empty or inactive.

![gradio_001](https://cloud.githubusercontent.com/assets/2544216/18419658/2fde3786-7860-11e6-85fb-5ab180361d32.png)

**Comment by haecker-felix** [comment]
Thanks. I can reproduce this bug. Fix is available soon.

**Comment by haecker-felix** [comment]
Fixed with the latest commit.

**Comment by mohamedsakhri** [comment]
According to my tests with the latest commits this bug is not fixed. It behaves like it is searching for an empty string!

![gradio_002](https://cloud.githubusercontent.com/assets/2544216/18615483/88f119b8-7da8-11e6-831b-993eaba698ab.png)
